global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hbase'

    static_configs:
      - targets: ['192.168.59.3:7000', '192.168.59.3:7001', '192.168.59.3:7002', '192.168.59.3:7003', '192.168.59.3:7004', '192.168.59.3:7005']
